version: '3.8'
services:
  mysql-auth:
    image: mysql:8.0
    container_name: bicap-auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bicap_auth_db
    ports:
      - "3308:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  auth_db_data:
