services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: bicap-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8.0
    container_name: bicap-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farm_production_db
    command: --default-authentication-plugin=mysql_native_password
