server:
  port: 8084

spring:
  datasource:
    url: ${spring.datasource.url:jdbc:mysql://localhost:3306/bicap_blockchain_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${spring.datasource.username:root}
    password: ${spring.datasource.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto:update}
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    database-platform: ${spring.jpa.database-platform:org.hibernate.dialect.MySQLDialect}
  
  # Cấu hình RabbitMQ khớp với các service khác
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:root}
    password: ${SPRING_RABBITMQ_PASSWORD:root}

# SỬA: Định nghĩa tên Queue khớp với Farm Service
bicap:
  rabbitmq:
    queue:
      request: farm_request_queue
      response: farm_response_queue
    exchange: bicap_exchange
    routing-key:
      response: bicap_routing_key_response
      request: bicap_routing_key_request
