version: "3.9"
services:
  mysql-farm:
    image: mysql:8.0
    container_name: mysql-farm-production
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farm_production_db
    ports:
      - "4307:3306"  
    volumes:
      - ./bicap_farm_db.sql:/docker-entrypoint-initdb.d/01_bicap_farm_db.sql
    networks:
      - bicap-net

networks:
  bicap-net:
    driver: bridge
